const std = @import("std");

const scm_suffix = ".scm";
const kata_suffix = ".kata";
const max_rule_bytes: usize = 1 * 1024 * 1024;
const output_buffer_size: usize = 8192;

const Args = struct {
    rules_dir: []const u8,
    output_path: []const u8,
};

const Entry = struct {
    lang: []const u8,
    id: []const u8,
    body: []const u8,
    format: []const u8,
};

const generated_header =
    \\// Code generated by tools/gen_embedded_rules.zig. DO NOT EDIT.
    \\
    \\pub const Format = enum { scm, kata };
    \\
    \\pub const Entry = struct {
    \\    id: []const u8,
    \\    source: []const u8,
    \\    format: Format,
    \\};
    \\
    \\
;

pub fn main(init: std.process.Init) !void {
    const arena_alloc = init.arena.allocator();
    const io = init.io;

    const args = try parseArgs(init, io);

    var entries: std.ArrayList(Entry) = .empty;
    defer entries.deinit(arena_alloc);
    try collectEntries(arena_alloc, io, args.rules_dir, &entries);

    std.mem.sort(Entry, entries.items, {}, entryLessThan);
    try writeOutput(io, args.output_path, entries.items);
}

fn parseArgs(init: std.process.Init, io: std.Io) !Args {
    const argv = try init.minimal.args.toSlice(init.arena.allocator());
    if (argv.len != 3) {
        try std.Io.File.stderr().writeStreamingAll(io, "usage: gen_embedded_rules <rules_dir> <output_file>\n");
        std.process.exit(2);
    }
    return .{ .rules_dir = argv[1], .output_path = argv[2] };
}

fn collectEntries(
    arena: std.mem.Allocator,
    io: std.Io,
    rules_dir_abs: []const u8,
    entries: *std.ArrayList(Entry),
) !void {
    var root_dir = try std.Io.Dir.openDirAbsolute(io, rules_dir_abs, .{ .iterate = true });
    defer root_dir.close(io);

    var root_iter = root_dir.iterate();
    while (try root_iter.next(io)) |dir_entry| {
        if (dir_entry.kind != .directory) continue;
        const dir_name = try arena.dupe(u8, dir_entry.name);
        try collectLangEntries(arena, io, &root_dir, dir_name, entries);
    }
}

fn collectLangEntries(
    arena: std.mem.Allocator,
    io: std.Io,
    root_dir: *std.Io.Dir,
    dir_name: []const u8,
    entries: *std.ArrayList(Entry),
) !void {
    var lang_dir = try root_dir.openDir(io, dir_name, .{ .iterate = true });
    defer lang_dir.close(io);

    var rule_iter = lang_dir.iterate();
    while (try rule_iter.next(io)) |rule_entry| {
        if (rule_entry.kind != .file) continue;
        const format = formatOf(rule_entry.name) orelse continue;

        const id = try arena.dupe(u8, stripSuffix(rule_entry.name, format));
        const body = try lang_dir.readFileAlloc(io, rule_entry.name, arena, .limited(max_rule_bytes));

        var it = std.mem.splitScalar(u8, dir_name, '+');
        while (it.next()) |lang| {
            try entries.append(arena, .{ .lang = try arena.dupe(u8, lang), .id = id, .body = body, .format = format });
        }
    }
}

fn formatOf(name: []const u8) ?[]const u8 {
    if (std.mem.endsWith(u8, name, scm_suffix)) return "scm";
    if (std.mem.endsWith(u8, name, kata_suffix)) return "kata";
    return null;
}

fn stripSuffix(name: []const u8, format: []const u8) []const u8 {
    const len = if (std.mem.eql(u8, format, "scm")) scm_suffix.len else kata_suffix.len;
    return name[0 .. name.len - len];
}

fn entryLessThan(_: void, a: Entry, b: Entry) bool {
    const lang_cmp = std.mem.order(u8, a.lang, b.lang);
    if (lang_cmp != .eq) return lang_cmp == .lt;
    return std.mem.order(u8, a.id, b.id) == .lt;
}

fn writeOutput(io: std.Io, output_path: []const u8, entries: []const Entry) !void {
    var out = try std.Io.Dir.createFileAbsolute(io, output_path, .{ .truncate = true });
    defer out.close(io);

    var buf: [output_buffer_size]u8 = undefined;
    var out_writer = out.writer(io, &buf);
    const w = &out_writer.interface;

    try w.writeAll(generated_header);

    var current_lang: []const u8 = "";
    var in_block = false;
    for (entries) |entry| {
        if (!std.mem.eql(u8, entry.lang, current_lang)) {
            if (in_block) try w.writeAll("};\n\n");
            try w.print("pub const embedded_{s}: []const Entry = &.{{\n", .{entry.lang});
            current_lang = entry.lang;
            in_block = true;
        }
        try writeEntry(w, entry);
    }
    if (in_block) try w.writeAll("};\n");

    try w.flush();
}

fn writeEntry(w: *std.Io.Writer, entry: Entry) !void {
    try w.print("    .{{\n        .id = \"{s}\",\n        .format = .{s},\n        .source =\n", .{ entry.id, entry.format });
    try writeAsMultilineLiteral(w, entry.body);
    try w.writeAll("        ,\n    },\n");
}

fn writeAsMultilineLiteral(w: *std.Io.Writer, body: []const u8) !void {
    var start: usize = 0;
    var i: usize = 0;
    while (i < body.len) : (i += 1) {
        if (body[i] == '\n') {
            try w.print("            \\\\{s}\n", .{body[start..i]});
            start = i + 1;
        }
    }
    if (start < body.len) {
        try w.print("            \\\\{s}\n", .{body[start..body.len]});
    }
}
