const std = @import("std");

const max_json_bytes: usize = 8 * 1024 * 1024;
const output_buffer_size: usize = 64 * 1024;

const Args = struct {
    output_path: []const u8,
    specs: []const FamilySpec,
};

const FamilySpec = struct {
    name: []const u8,
    paths: []const []const u8,
};

const Family = struct {
    name: []const u8,
    named: []const []const u8,
    anon: []const []const u8,
    fields: []const []const u8,
};

const generated_header =
    \\// Code generated by pkg/gen-node-kinds/main.zig. DO NOT EDIT.
    \\
    \\const std = @import("std");
    \\const ts = @import("tree_sitter");
    \\
    \\
;

const family_helpers =
    \\
    \\    pub fn name(id: u16) []const u8 {
    \\        if (id == 0 or id >= kind_count) return kind_names[0];
    \\        if (id < anon_base) return kind_names[id];
    \\        return anon_names[id - anon_base];
    \\    }
    \\
    \\    pub fn buildKindRemap(grammar: *const ts.Language, gpa: std.mem.Allocator) ![]u16 {
    \\        const remap = try gpa.alloc(u16, grammar.nodeKindCount());
    \\        @memset(remap, 0);
    \\        inline for (@typeInfo(Kind).@"enum".fields) |f| {
    \\            if (f.value != 0) {
    \\                const sym = grammar.idForNodeKind(f.name, true);
    \\                if (sym != 0) remap[sym] = f.value;
    \\            }
    \\        }
    \\        for (anon_names, 0..) |token, i| {
    \\            const sym = grammar.idForNodeKind(token, false);
    \\            if (sym != 0) remap[sym] = anon_base + @as(u16, @intCast(i));
    \\        }
    \\        return remap;
    \\    }
    \\
    \\    pub fn buildFieldRemap(grammar: *const ts.Language, gpa: std.mem.Allocator) ![]u16 {
    \\        const remap = try gpa.alloc(u16, grammar.fieldCount() + 1);
    \\        @memset(remap, 0);
    \\        inline for (@typeInfo(Field).@"enum".fields) |f| {
    \\            if (f.value != 0) {
    \\                const id = grammar.fieldIdForName(f.name);
    \\                if (id != 0) remap[id] = f.value;
    \\            }
    \\        }
    \\        return remap;
    \\    }
    \\
;

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    const argv = try init.minimal.args.toSlice(arena);
    const args = parseArgs(arena, argv) catch {
        try std.Io.File.stderr().writeStreamingAll(io, "usage: gen_node_kinds <output_file> (<family> <count> <node_types.json>...)+\n");
        std.process.exit(2);
    };

    var families: std.ArrayList(Family) = .empty;
    for (args.specs) |spec| {
        try families.append(arena, try collectFamily(arena, io, spec));
    }

    try writeOutput(io, args.output_path, families.items);
}

fn parseArgs(arena: std.mem.Allocator, argv: []const [:0]const u8) !Args {
    if (argv.len < 5) return error.InvalidArgs;

    var specs: std.ArrayList(FamilySpec) = .empty;
    var i: usize = 2;
    while (i < argv.len) {
        if (i + 2 > argv.len) return error.InvalidArgs;
        const count = std.fmt.parseInt(usize, argv[i + 1], 10) catch return error.InvalidArgs;
        if (count == 0 or i + 2 + count > argv.len) return error.InvalidArgs;

        var paths: std.ArrayList([]const u8) = .empty;
        for (argv[i + 2 .. i + 2 + count]) |path| try paths.append(arena, path);
        try specs.append(arena, .{ .name = argv[i], .paths = paths.items });
        i += 2 + count;
    }
    return .{ .output_path = argv[1], .specs = specs.items };
}

fn collectFamily(arena: std.mem.Allocator, io: std.Io, spec: FamilySpec) !Family {
    var named: std.ArrayList([]const u8) = .empty;
    var anon: std.ArrayList([]const u8) = .empty;
    var fields: std.ArrayList([]const u8) = .empty;

    for (spec.paths) |path| {
        const body = try std.Io.Dir.cwd().readFileAlloc(io, path, arena, .limited(max_json_bytes));
        try collectNodeTypes(arena, body, &named, &anon, &fields);
    }

    return .{
        .name = spec.name,
        .named = try sortDedupe(arena, named.items),
        .anon = try sortDedupe(arena, anon.items),
        .fields = try sortDedupe(arena, fields.items),
    };
}

fn collectNodeTypes(
    arena: std.mem.Allocator,
    body: []const u8,
    named: *std.ArrayList([]const u8),
    anon: *std.ArrayList([]const u8),
    fields: *std.ArrayList([]const u8),
) !void {
    const parsed = try std.json.parseFromSlice(std.json.Value, arena, body, .{});
    if (parsed.value != .array) return error.MalformedNodeTypes;

    for (parsed.value.array.items) |entry| {
        if (entry != .object) return error.MalformedNodeTypes;
        const obj = entry.object;

        const type_name = stringField(obj, "type") orelse return error.MalformedNodeTypes;
        const is_named = boolField(obj, "named") orelse return error.MalformedNodeTypes;

        if (obj.get("fields")) |fields_value| {
            if (fields_value != .object) return error.MalformedNodeTypes;
            for (fields_value.object.keys()) |key| try fields.append(arena, try arena.dupe(u8, key));
        }

        if (!is_named) {
            try anon.append(arena, try arena.dupe(u8, type_name));
            continue;
        }
        if (obj.get("subtypes") != null) continue;
        try named.append(arena, try arena.dupe(u8, type_name));
    }
}

fn stringField(obj: std.json.ObjectMap, key: []const u8) ?[]const u8 {
    const value = obj.get(key) orelse return null;
    if (value != .string) return null;
    return value.string;
}

fn boolField(obj: std.json.ObjectMap, key: []const u8) ?bool {
    const value = obj.get(key) orelse return null;
    if (value != .bool) return null;
    return value.bool;
}

fn sortDedupe(arena: std.mem.Allocator, items: [][]const u8) ![]const []const u8 {
    std.mem.sort([]const u8, items, {}, stringLessThan);

    var out: std.ArrayList([]const u8) = .empty;
    for (items) |item| {
        if (out.items.len > 0 and std.mem.eql(u8, out.items[out.items.len - 1], item)) continue;
        try out.append(arena, item);
    }
    return out.items;
}

fn stringLessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.order(u8, a, b) == .lt;
}

fn writeOutput(io: std.Io, output_path: []const u8, families: []const Family) !void {
    var out = try std.Io.Dir.createFileAbsolute(io, output_path, .{ .truncate = true });
    defer out.close(io);

    var buf: [output_buffer_size]u8 = undefined;
    var out_writer = out.writer(io, &buf);
    const w = &out_writer.interface;

    try w.writeAll(generated_header);
    for (families, 0..) |family, i| {
        if (i > 0) try w.writeAll("\n");
        try writeFamily(w, family);
    }

    try w.flush();
}

fn writeFamily(w: *std.Io.Writer, family: Family) !void {
    try w.print("pub const {s} = struct {{\n", .{family.name});

    try w.writeAll("    pub const Kind = enum(u16) {\n        unknown = 0,\n");
    for (family.named) |kind| try w.print("        {s},\n", .{kind});
    try w.writeAll("    };\n\n");

    try w.writeAll("    pub const Field = enum(u16) {\n        none = 0,\n");
    for (family.fields) |field| try w.print("        {s},\n", .{field});
    try w.writeAll("    };\n\n");

    try w.print("    pub const named_count: u16 = {d};\n", .{family.named.len});
    try w.writeAll(
        \\    pub const anon_base: u16 = named_count + 1;
        \\    pub const kind_count: u16 = anon_base + anon_names.len;
        \\
        \\    pub const kind_names = [anon_base][]const u8{
        \\        "ERROR",
        \\
    );
    for (family.named) |kind| try writeQuoted(w, kind);
    try w.writeAll("    };\n\n    pub const anon_names = [_][]const u8{\n");
    for (family.anon) |token| try writeQuoted(w, token);
    try w.writeAll("    };\n");

    try w.writeAll(family_helpers);
    try w.writeAll("};\n");
}

fn writeQuoted(w: *std.Io.Writer, text: []const u8) !void {
    try w.writeAll("        \"");
    for (text) |char| {
        switch (char) {
            '"' => try w.writeAll("\\\""),
            '\\' => try w.writeAll("\\\\"),
            '\n' => try w.writeAll("\\n"),
            '\r' => try w.writeAll("\\r"),
            '\t' => try w.writeAll("\\t"),
            0x20...0x21, 0x23...0x5b, 0x5d...0x7e => try w.writeByte(char),
            else => try w.print("\\x{x:0>2}", .{char}),
        }
    }
    try w.writeAll("\",\n");
}
